fix: prevent missing index signature
  Error: src/app/app.component.html:2:15 - error TS2322: Type 'Post[] | null' is not assignable to type 'DataRow[] | null'.
    Type 'Post[]' is not assignable to type 'DataRow[]'.
      Type 'Post' is not assignable to type 'DataRow'.
        Index signature is missing in type 'Post'.

  2   <app-table [dataRows]="posts$ | async"></app-table>
                  ~~~~~~~~

    src/app/app.component.ts:10:16
      10   templateUrl: "./app.component.html",
                        ~~~~~~~~~~~~~~~~~~~~~~
      Error occurs in the template of component AppComponent.